INSERT INTO Sales (zip_code,lat, lang, seller_id ,city_name, code_state,product_id, order_item, price, shipping_limit_date)
SELECT top 500000 olist_geolocation_dataset.geolocation_zip_code_prefix, 
olist_geolocation_dataset.geolocation_lat,
olist_geolocation_dataset.geolocation_lng, 
olist_sellers_dataset.seller_id,
olist_sellers_dataset.seller_city, 
olist_sellers_dataset.seller_state,
olist_order_items_dataset.product_id,
olist_order_items_dataset.order_item_id,
olist_order_items_dataset.price,
olist_order_items_dataset.shipping_limit_date
FROM olist_sellers_dataset
FULL OUTER JOIN olist_geolocation_dataset
ON olist_geolocation_dataset.geolocation_zip_code_prefix = olist_sellers_dataset.seller_zip_code_prefix
FULL OUTER JOIN olist_order_items_dataset
ON olist_sellers_dataset.seller_id = olist_order_items_dataset.seller_id